### ISSUE TITLE
Convert VCF to mdp_SNP_information.txt and mdp_numeric.txt

### ISSUE THREAD

**Issue by mullerbsf** [amkusmec/FarmCPUpp#2]
Dear,

Is there any script available to convert a VCF file automatically into the mdp_SNP_information.txt and mdp_numeric.txt files?

Thank you!

**Comment by amkusmec** [comment]
Hi Barbara,

The following code fragment should accomplish the conversion and account for the use of (un)phased genotypes in the VCF file. Note that this will count the number of ALTERNATE alleles not minor alleles as is typically done for GWAS. You may need to recode the REF/ALT alleles if you want to count only minor alleles. Another thing to be aware of is that this assumes biallelic SNPs, coded as 0/1 REF/ALT in the VCF file. If you have 3+ alleles, then you'll have calls of 3, 4, etc. that will throw off the coding.

```
library(tidyverse)

# Load the file (also works for g- or bzipped files)
snps <- read_tsv("snp_file.vcf", comment = "##") %>%
  arrange(`#CHROM`, POS)

# Sample names
taxa <- names(snps)[-c(1:9)]

# Keep SNP information
GM <- snps[, 1:9] %>%
  rename(Chromosome = `#CHROM`, Position = POS, SNP = ID) %>%
  mutate(SNP = make.names(SNP)) %>%
  select(SNP, Chromosome, Position)

# Swap dimensions so that samples are rows and SNPs are columns
snps <- t(snps[, -c(1:9)])
colnames(snps) <- GM$SNP
rownames(snps) <- taxa

# Convert to numeric genotypes
snps <- apply(snps, 2, function(x) {
  if_else(x == "0|0" | x == "0/0", 0, 
          if_else(x == "0|1" | x == "1|0" | x == "0/1" | x == "1/0", 1, 2))
})
rownames(snps) <- taxa
```

**Comment by mullerbsf** [comment]
Dear Aaron,

How this code handle missing data (“./.”)?

Does it matter for multi-SNP GWAS, as FarmCPUpp, the alternate allele is not a minor allele? It will be hard to account for the allele frequency and then do the conversion for FarmCPUpp.

Are you able to generate a version of FarmCPUpp using a VCF file directly? Will it be more user-friendly, and no need to handle the allele frequency for major or minor alleles conversion.

Thank you very much!
Barbara.

**Comment by amkusmec** [comment]
This code doesn't handle missing data. FarmCPUpp requires that all genotypes be non-missing. You could do imputation with a program like BEAGLE or simply replace missing genotypes with twice the minor/alternate allele frequency.

For the mechanics of doing GWAS, which allele you count does not matter. For the interpretation it does. You can look at Chapter 7 of Falconer and Mackay or Chapter 3 of Rex Bernardo's "Breeding for Quantitative Traits in Plants" for a description of the calculation and interpretation of allele substitution effects.

FarmCPUpp is not under active development right now. It was designed as a fairly bare-bones package; any quality control and formatting issues are up to the user. Since you have a VCF file, an alternative would be to convert that to a BED file using PLINK and then the `BEDMatrix` package to get it into R.
