### ISSUE TITLE
Errors at loop:2 with "NAs introduced by coercion"

### ISSUE THREAD

**Issue by ttian627** [amkusmec/FarmCPUpp#4]
There are my log information, my input test files were execute correctly using famcpu. What could be the reason for the errors? Thank you.

------------------------------ Welcome to FarmCPU ------------------------------
Version 1.2.0

Current loop: 1 / 10
Removing highly correlated pseudo-QTNs.
pseudo-QTNs:

Number of covariates in current loop: 0
Scanning...
GLM time: 2.697 (s)
Substituting pseudo-QTN p-values with method reward.

Current loop: 2 / 10
Static selection of 20 QTNs in 5e+07 length bins.
Error in GI[, 2] * MaxBP : non-numeric argument to binary operator
Calls: farmcpu -> get_qtns -> get_bins
In addition: Warning message:
In get_bins(GI = GM, GP = cbind(GM, P), bin.size = bin.sizes, nqtn = nqtn) :
  NAs introduced by coercion
Execution halted

**Comment by amkusmec** [comment]
This is a note on the resolution of this particular error since it's rather common:

Per the "Date formats" section of the readme, the second column of the genotype information data frame (`GM` in the function arguments) contains the chromosome identifiers. Those need to be numeric- or integer-type for the binning function to work properly. The error indicates that the input probably has character-type chromosome IDs.

Users should check that their data meet the proper requirements by examining the documentation. The program *could* convert to integer/numeric internally, but if that creates NA values, the resulting binning behavior won't be what the user expects. It's therefore preferable to terminate with an error.
